apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.targetPort }}
  type: ClusterIP
